import { Star, CircleX, Check, Clock } from "lucide-react";
import BookingDetails from "@/app/requester/bookings/booking-details";
import TripDetails from "@/app/driver/trips/trip-details";
import ExpenseDetails from "@/app/driver/expense/expense-details";
import RequestDetails from "@/app/driver/request-absence/request-details";
import ActivityDetails from "@/app/driver/executive/activity-details";
import ExecutiveActivityDetails from "@/app/executive/activities/activity-details";
import { ViewExpense } from "@/app/dashboard/expenses/_components/view";
import { TripView } from "@/app/dashboard/trips/_components/trip-form";
import { ViewVsr } from "@/app/dashboard/vehicle-service-requests/_components/view";
import { LeaveRequestView } from "@/app/dashboard/leave-requests/_components/view";
import { ViewTripFeedbacks } from "@/app/dashboard/feedbacks/_components/view";

// Role-based notification key mapping for styling and highlighting
export const NOTIFICATION_CONFIG = {
	Employee: {
		"trip-reminder": {
			type: "departure",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["tomorrow", "ngày mai"],
			component: BookingDetails,
		},
		"booking-request-approve": {
			type: "approved",
			icon: Check,
			bgColor: "bg-success",
			textColor: "text-success",
			highlightWords: ["approved", "finalized", "phê duyệt", "được chốt"],
			component: BookingDetails,
		},
		"booking-request-modified-by-coordinator": {
			type: "general",
			icon: Clock,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["modified", "điều chỉnh"],
			component: BookingDetails,
		},
		"booking-request-cancel-by-coordinator": {
			type: "cancelled",
			icon: CircleX,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["cancelled", "huỷ"],
			component: BookingDetails,
		},
		"booking-request-rejected-by-coordinator": {
			type: "cancelled",
			icon: CircleX,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["rejected", "từ chối"],
			component: BookingDetails,
		},
		"user-info-updated": {
			type: "general",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["updated", "cập nhật"],
			component: null,
		},
	},
	Coordinator: {
		"coordinator-booking-request-approval": {
			type: "general",
			icon: Clock,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["approval", "phê duyệt"],
			component: BookingDetails,
		},
		"coordinator-leave-request-submit": {
			type: "general",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["submitted", "được gửi", "đã gửi"],
			component: LeaveRequestView,
		},
		"coordinator-trip-success": {
			type: "approved",
			icon: Check,
			bgColor: "bg-success",
			textColor: "text-success",
			highlightWords: ["successfully", "thành công"],
			component: TripView,
		},
		"coordinator-expense-review": {
			type: "general",
			icon: Clock,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["review", "submitted", "xem xét", "đã gửi"],
			component: ViewExpense,
		},
		"coordinator-vehicle-service-review": {
			type: "general",
			icon: Clock,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["review", "submitted", "xem xét", "yêu cầu"],
			component: ViewVsr,
		},
		"coordinator-bad-rating-alert": {
			type: "rate",
			icon: Star,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["alert", "received rating", "cảnh báo", "nhận được đánh giá"],
			component: ViewTripFeedbacks,
		},
		"urgent-booking-request": {
			type: "general",
			icon: Star,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["urgent", "khẩn cấp"],
			component: BookingDetails,
		},
		"vip-booking-request": {
			type: "general",
			icon: Star,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["VIP", "quan trọng"],
			component: BookingDetails,
		},
		"new-booking-request": {
			type: "general",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["submitted", "xử lí"],
			component: BookingDetails,
		},
		"coordinator-booking-request-updated": {
			type: "general",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["updated", "cập nhật"],
			component: BookingDetails,
		},
		"coordinator-urgent-booking-request-updated": {
			type: "general",
			icon: Star,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["updated", "cập nhật"],
			component: BookingDetails,
		},
		"coordinator-vip-booking-request-updated": {
			type: "general",
			icon: Star,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["updated", "cập nhật"],
			component: BookingDetails,
		},
		"booking-request-no-vehicle-available": {
			type: "general",
			icon: CircleX,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["no vehicle", "không có xe"],
			component: BookingDetails,
		},
		"trip-reminder": {
			type: "departure",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["tomorrow", "ngày mai"],
			component: BookingDetails,
		},
		"booking-request-approve": {
			type: "approved",
			icon: Check,
			bgColor: "bg-success",
			textColor: "text-success",
			highlightWords: ["approved", "finalized", "phê duyệt", "được chốt"],
			component: BookingDetails,
		},
		"booking-request-modified-by-coordinator": {
			type: "general",
			icon: Clock,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["modified", "điều chỉnh"],
			component: BookingDetails,
		},
		"booking-request-cancel-by-coordinator": {
			type: "cancelled",
			icon: CircleX,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["cancelled", "huỷ"],
			component: BookingDetails,
		},
		"booking-request-rejected-by-coordinator": {
			type: "cancelled",
			icon: CircleX,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["rejected", "từ chối"],
			component: BookingDetails,
		},
		"user-info-updated": {
			type: "general",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["updated", "cập nhật"],
			component: null,
		},
	},
	Admin: {
		"coordinator-booking-request-approval": {
			type: "general",
			icon: Clock,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["approval", "phê duyệt"],
			component: BookingDetails,
		},
		"coordinator-leave-request-submit": {
			type: "general",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["submitted", "được gửi", "đã gửi"],
			component: LeaveRequestView,
		},
		"coordinator-trip-success": {
			type: "approved",
			icon: Check,
			bgColor: "bg-success",
			textColor: "text-success",
			highlightWords: ["successfully", "thành công"],
			component: TripView,
		},
		"coordinator-expense-review": {
			type: "general",
			icon: Clock,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["review", "submitted", "xem xét", "đã gửi"],
			component: ViewExpense,
		},
		"coordinator-vehicle-service-review": {
			type: "general",
			icon: Clock,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["review", "submitted", "xem xét", "yêu cầu"],
			component: ViewVsr,
		},
		"coordinator-bad-rating-alert": {
			type: "rate",
			icon: Star,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["alert", "received rating", "cảnh báo", "nhận được đánh giá"],
			component: ViewTripFeedbacks,
		},
		"urgent-booking-request": {
			type: "general",
			icon: Star,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["urgent", "khẩn cấp"],
			component: BookingDetails,
		},
		"vip-booking-request": {
			type: "general",
			icon: Star,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["VIP", "quan trọng"],
			component: BookingDetails,
		},
		"new-booking-request": {
			type: "general",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["submitted", "xử lí"],
			component: BookingDetails,
		},
		"coordinator-booking-request-updated": {
			type: "general",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["updated", "cập nhật"],
			component: BookingDetails,
		},
		"coordinator-urgent-booking-request-updated": {
			type: "general",
			icon: Star,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["updated", "cập nhật"],
			component: BookingDetails,
		},
		"coordinator-vip-booking-request-updated": {
			type: "general",
			icon: Star,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["updated", "cập nhật"],
			component: BookingDetails,
		},
		"booking-request-no-vehicle-available": {
			type: "general",
			icon: CircleX,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["no vehicle", "không có xe"],
			component: BookingDetails,
		},
		"trip-reminder": {
			type: "departure",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["tomorrow", "ngày mai"],
			component: BookingDetails,
		},
		"booking-request-approve": {
			type: "approved",
			icon: Check,
			bgColor: "bg-success",
			textColor: "text-success",
			highlightWords: ["approved", "finalized", "phê duyệt", "được chốt"],
			component: BookingDetails,
		},
		"booking-request-modified-by-coordinator": {
			type: "general",
			icon: Clock,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["modified", "điều chỉnh"],
			component: BookingDetails,
		},
		"booking-request-cancel-by-coordinator": {
			type: "cancelled",
			icon: CircleX,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["cancelled", "huỷ"],
			component: BookingDetails,
		},
		"booking-request-rejected-by-coordinator": {
			type: "cancelled",
			icon: CircleX,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["rejected", "từ chối"],
			component: BookingDetails,
		},
		"user-info-updated": {
			type: "general",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["updated", "cập nhật"],
			component: null,
		},
	},
	Driver: {
		"driver-new-trip-assigned": {
			type: "general",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["assigned", "phân công"],
			component: TripDetails,
		},
		"driver-trip-information-changed": {
			type: "general",
			icon: Clock,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["updated", "cập nhật"],
			component: TripDetails,
		},
		"driver-trip-cancel": {
			type: "cancelled",
			icon: CircleX,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["Cancelled", "hủy"],
			component: TripDetails,
		},
		"driver-reminder": {
			type: "departure",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["reminder", "nhắc nhở"],
			component: TripDetails,
		},
		"driver-logged-expenses": {
			type: "general",
			icon: Clock,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["review", "xem xét"],
			component: ExpenseDetails,
		},
		"driver-expenses-approved": {
			type: "approved",
			icon: Check,
			bgColor: "bg-success",
			textColor: "text-success",
			highlightWords: ["approved", "phê duyệt"],
			component: ExpenseDetails,
		},
		"driver-expenses-rejected": {
			type: "cancelled",
			icon: Check,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["rejected", "từ chối"],
			component: ExpenseDetails,
		},
		"driver-leave-approved": {
			type: "approved",
			icon: Check,
			bgColor: "bg-success",
			textColor: "text-success",
			highlightWords: ["approved", "phê duyệt"],
			component: RequestDetails,
		},
		"driver-leave-rejected": {
			type: "cancelled",
			icon: CircleX,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["rejected", "từ chối"],
			component: RequestDetails,
		},
		"driver-maintenance-approved": {
			type: "approved",
			icon: Check,
			bgColor: "bg-success",
			textColor: "text-success",
			highlightWords: ["approved", "phê duyệt"],
			component: RequestDetails,
		},
		"driver-maintenance-rejected": {
			type: "cancelled",
			icon: CircleX,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["rejected", "từ chối"],
			component: RequestDetails,
		},
		"driver-vehicle-service-approved": {
			type: "approved",
			icon: Check,
			bgColor: "bg-success",
			textColor: "text-success",
			highlightWords: ["approved", "phê duyệt"],
			component: RequestDetails,
		},
		"driver-vehicle-service-rejected": {
			type: "cancelled",
			icon: CircleX,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["rejected", "từ chối"],
			component: RequestDetails,
		},
		"driver-activity-log-approved": {
			type: "approved",
			icon: Check,
			bgColor: "bg-success",
			textColor: "text-success",
			highlightWords: ["approved", "phê duyệt"],
			component: ActivityDetails,
		},
		"driver-activity-log-rejected": {
			type: "cancelled",
			icon: CircleX,
			bgColor: "bg-destructive",
			textColor: "text-destructive",
			highlightWords: ["rejected", "từ chối"],
			component: ActivityDetails,
		},
		"driver-leave-request-submit-by-coordinator": {
			type: "general",
			icon: Clock,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["submitted", "check", "được tạo", "kiểm tra"],
			component: RequestDetails,
		},
		"driver-expense-submit-by-coordinator": {
			type: "general",
			icon: Clock,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["submitted", "check", "được tạo", "kiểm tra"],
			component: ExpenseDetails,
		},
		"driver-vehicle-service-submit-by-coordinator": {
			type: "general",
			icon: Clock,
			bgColor: "bg-warning",
			textColor: "text-warning",
			highlightWords: ["submitted", "check", "được tạo", "kiểm tra"],
			component: RequestDetails,
		},
	},
	Executive: {
		"executive-receive-activity-log": {
			type: "general",
			icon: Clock,
			bgColor: "bg-info",
			textColor: "text-info",
			highlightWords: ["received", "đã nhận", "đã gửi"],
			component: ExecutiveActivityDetails,
		},
	},
} as const;
